name: town

on:
  pull_request:
    branches:
      - '**'

jobs:
  git-town:
    name: display the branch stack
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: git-town/action@v1
